### ISSUE TITLE
ScanFailure

### ISSUE THREAD

**Issue by agarnet74** [antigones/flutter_arduino_nano_33_ble#1]
Hi,
I have this error :
I/flutter ( 6131): Exception: GenericFailure(code: ScanFailure.unknown, message: "Location Permission missing (code 3)")

Any idea how to solve this ?

Thanks

**Comment by antigones** [comment]
Hello, you must enable geolocation on the device and request permission for geolocation.

**Comment by agarnet74** [comment]
Yes, that's it, I just found out, thank you very much
