### ISSUE TITLE
Undocumented scan throttle

### ISSUE THREAD

**Issue by jpdelvalle** [antigones/flutter_arduino_nano_33_ble#2]
Hello

I'm trying to run this code and it throws me this error:

I/flutter ( 2427): Exception: GenericFailure<ScanFailure>(code: ScanFailure.unknown, message: "Undocumented scan throttle (code 2147483646)

I have both geolocation and blutooth available

**Comment by antigones** [comment]
Hello,
googling the error, it seems related to the fact that it is not possible to start more than 5 scans during a 30 seconds window.

See also this issues: https://github.com/dotintent/react-native-ble-plx/issues/222
And this medium article: https://blog.classycode.com/undocumented-android-7-ble-behavior-changes-d1a9bd87d983
